[package]
name = "rusty-2048-tui"
license = "MIT license"
description = "Interactive 2048 game using the Ratatui library"
readme = "README.md"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
rusty-2048 = { path = "../rusty-2048", version = "0.1.0" }